### ISSUE TITLE
EOF while parsing

### ISSUE THREAD

**Issue by clevernyyyy** [vihanggodbole/reddit-pocket-sync#1]
I'm getting to the point where I authorize Pocket, but after I hit 'enter' to the input - I get the following error.

```
reddit-pocket-sync/PocketUser.py", line 41, in login
    input('Once you have authorized your account in the web browser, please press any to continue...')
  File "<string>", line 0
    
    ^
SyntaxError: unexpected EOF while parsing
```

I'm super excited to try to get this working because it's exactly what I'm looking for, but not sure what's happening here.  Ideas?

**Comment by vihanggodbole** [comment]
Are you using Python 2 by any chance?

**Comment by clevernyyyy** [comment]
Ah, yes I was.  Switched to `python3 reddit-pocket-sync.py` and it worked fine, thank you!  One other question real quick - what's the point for redirecting to 127.0.0.1:5000 after oAuth from Pocket?
https://github.com/vihanggodbole/reddit-pocket-sync/blob/master/PocketUser.py#L22

**Comment by vihanggodbole** [comment]
To be honest I didn't quite know how to redirect the user back to a terminal script window from the browser so I just redirected it to the localhost. If you want a bit more polish you could redirect the user to `https://www.reddit.com`. In any case it doesn't matter since we already obtain the refresh token needed for OAuth authentication.
Thank you for using this btw and I'm glad you found it useful.
